### ISSUE TITLE
ValueError: Error from jshint

### ISSUE THREAD

**Issue by janskey** [SublimeLinter/SublimeLinter-for-ST2#648]
Hi, what does the errors mean https://gist.github.com/janskey/c812b94006392760b4f6

Since SublimeLinter for ST-2 is not supported in PackageControl i just clone it to my package folder. By the way, the linter doesn't work

**Comment by janskey** [comment]
i tried to remove and install it again and saw this in the console https://gist.github.com/janskey/cf0a98f4a118e184d38a

**Comment by juliandescottes** [comment]
Hi,

For your first error, I experienced the same thing.

It is linked to Node 0.12, which deprecated `util.puts` in favor of `console.log`.

See https://github.com/joyent/node/blob/master/doc/api/util.markdown#utildeprecatefunction-string

As a workaround, you can either downgrade your node install to 0.11.

To fix this, the two calls to `util.puts` in https://github.com/SublimeLinter/SublimeLinter-for-ST2/blob/master/sublimelinter/modules/libs/jsengines/node.js should be replaced with `console.log`.

**Comment by skj3gg** [comment]
fixed with version release 1.8.0
